version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: |
            echo "Installing dependencies..."
            npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            npm run test
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            echo "Building and pushing Docker image..."
            docker build -t my-image:latest .
            docker push my-image:latest
workflows:
  build-and-test:
    jobs:
      - build
      - test
      - publish