# Test Main Branch
version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: robinyms101/node-app-for-devops
      - docker/push:
          image: robinyms101/node-app-for-devops

  deploy:
    docker:
      - image: cimg/node:23.11.0
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a robinyms-su-devops
            heroku container:push web -a robinyms-su-devops
            heroku container:release web -a robinyms-su-devops

workflows:
  ci-cd-pipeline:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - release

      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release

      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - release

      - deploy:
          requires:
            - publish
          filters:
            branches:
              only:
                - release