# Test github action
name: "Test github action"

on: 
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: "22.x"
                cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Simulate build
              run: echo "Simulate build"
      
    test:
      needs: build # This job runs after the build job completes
      runs-on: ubuntu-latest
      steps:
        # Similar setup to build job
        - uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: "16.x"
            cache: "npm"
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: |
            echo "Running tests..."
            npm run test  # Runs the test script from package.json

    publish:
      needs: test # This job runs after the test job completes
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2 # Sets up Docker build system
        - name: Login to Docker Hub
          uses: docker/login-action@v2 # Logs in to Docker Hub
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }} # Uses repository secrets
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4 # Builds and pushes Docker image
          with:
            context: .
            push: true
            tags: robinyms101/node-app-for-devops:latest # Tags the Docker image